# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Utt602pkPQJo3A==,iv:4C5KO/c4cKFBqv3PI3ZCRHr8Et/wpvQT3nr7d8FtL0c=,tag:RX/GPtGff2r1yG4R+YWHtw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:tZSHrpr09VuNrDbbuL8U83MZ/pG+i88Qfo18WT8=,iv:tZBh5A+fmJ8ZdcDOXe1y0chqw4hDetWgEbUNw7sfb2o=,tag:ODpNKqfV4qheB+OCen5N0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-05T14:27:38Z"
    mac: ENC[AES256_GCM,data:scLhokNroLQ4yOrryVd9rblWXxD/3tcbVWsdrokwYKW5zS1JTYVZDvjhiH/RWyEUevjqKTGXL8dzS9oJRDFkpTnIO2ioDZ1IZSL3LjJ9Nu3/Uf0+TOt8MDcE5vMfIVdet9NHsUgzP6ycUf0HaloPgaJwtvh2a6UUJ+CZFUws880=,iv:6Q/7tqLMsEPJ/QA3IbUX5a+gkc4GqZRmi9zEY9h3gKw=,tag:K3Gyb/PDlaEZl4YwJG89pQ==,type:str]
    pgp:
        - created_at: "2021-09-05T14:27:37Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6p3jCZcYZ8MAQ//Q3LQ8LBXvhrQLEWacy80IBeZfUuRSi6F7C+iuQjfGPNG
            Aoey4nGmNuhIU61CGZUKyEwCTDjqtaHt0OWgiDQ6Itl4Z/9U7gpqVXAsE20+sV6B
            yctwNoRmidLC89QvDgj8JScaB0mVviQK/ToUyRxOIriQNP1rReh+mt+cooALgL6d
            s/h0Uoo7nFa4Kr1yVE4HWYjkN0EoTE5KLN1z1FOuSUGmN/oWbq28+cdnAJPC92tp
            H9Ne0sZsZFzDGhiCH/t30Spw5OR2y9SHxsOa6z/6GXY94Lwaedy5nCsCjI8Rk/Ut
            KtDjxn/hXpg+waudGGy6SF/4tWbeJc+ItqRgWtvRau6/CnFgqs6d4tcIPg7p/VoO
            pBgh9DsM/SMZYbgX5h/r2HnLrXHKP/3/GyUwERtkXXxyUlbAi8tzQSum6WklDezD
            C5tAc+vPA3nHpgX5Q2/pGkRLvVLDnXpo6ndhwfSNFlI55WIzSiFAwdJw46rVjeW8
            /GfBacKOIJtIjO/PoAKyp1SKuJj5RNQgsPGt6PZwof19chmUhVpaKwwgRt167RFE
            ZC0VbGZENznrX8futcE4mhu6L9r2ZmIzHQvXm5PTJiB1mloYndew7VWefCUlFjTH
            NHllZdEUH3d5pyizCkzEtfSbYK7uVueEBgkK2yItuyzD1ZlyQ4Uwo+2DaRE4PL/S
            XAH2qjHnzfgMkptFjqLi8rz0iAPpMcSrOtSF5TKS3IxvqFwu4RCX6vENisxFFmzh
            T60s/9RuCbtV7RnTLqMa3v/n8Cdyg5KdtYDsz368cJwAY8m3QIkKseMAZyVi
            =2aDA
            -----END PGP MESSAGE-----
          fp: 473E92FCC1B19B623E24F1389F9D6BA271FF6A63
        - created_at: "2021-09-05T14:27:37Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1Mu2Wo4Op2VARAAnoU0nbbWQl88P0jXK+MtKVDw9a7PILa++D8EOwoNffwl
            d1YMMJcsUYNn8jnAbZA62XUQ1xJ4nxiitD6O4zAdD2qyzwx+RKpllbb0HEfzf1zO
            8ZPVgXQV+NHRRnS1Ec1mCbV5KmNPsdXEE4lSE9grGAdogzw15wlMGXh7sF3iIZd/
            JMSwk/Oi2gK0L/tUUZfrUUQm+jsUktpNa0VXU6ii5Qdf+PxZGVYcp+CrYXTCqFXt
            f9KrsgflwveHjLkfQu2S9pMWUy1Baxw5ix0zz7B3n17UuXPPlCvD6x7H4XoRE0PK
            NTc5P2Yx1WDWwZuU0ig3fKU98X/SBlZgFtADwXguEKWuD7PiXiA/mTJNQd06VFCD
            xICzPK4KyushXDY/zjJHNy+sQW0SZQho4/yHjEI7PWXiEQCcd4lpKjXUGVckoXRF
            uuj3QEIUFG2MhBj460FEaTfs3TYyUkNW+lEdsvADaPyHc7t94O7OlI1dfTHn/9Ch
            SjhEVTq6rEd9HuKFkKCmDMghCJ0yOGcOcsCHrYG0/QVEpKCsGcZtbtLSOgFBcM8Q
            Oo7QgupVuWgl+70u9vd9Q5dMnAuCLdbCgw69cwMhNgyAQL0KleUKQkdmXEekYARf
            wPxzXfdXsdu78jeQsA9sICZRGVD1CGur8GjZ6CK8k3M+Bds3VaWnjqHi4HO0n4jS
            XAFz1sgp+5wo+cTQfbDDTJrOooIE59cJie+EMkZ6rslZClIjhv417PLcRmZQvBns
            ke2kcKiIC90nzkctpOPVcVE2/j/FoJp8vWo8Bmu5gP5Vd/IUZP0CjV6Rtnor
            =JWGI
            -----END PGP MESSAGE-----
          fp: FC0B4DCED2CE5B598507991312C76065F613DD93
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
