# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:kih52CkihEQnNAvLEOdwESpha8h3+s/AchQL1rpr1xjsXvbmUu6jLQ==,iv:gGa944SFtO2ZcZ/BaIoNt87U+UPXCghZC5p8wXWJKTo=,tag:01k9POfdqTtKHNQ1IlWEMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-05T14:28:04Z"
    mac: ENC[AES256_GCM,data:iN+/3rehh8EuiptV8WRewRRhLU2wpgENBZobOXzIqDWRKhDtSqDx6jwsfa9lG/vL4xZ4t6z9UB2eIeZPzf3Z9hG4F5sq2r2rpYqcAOlCCGXh7ZnTZlZmcWQA520tmBBoRNlKV8kFTfD0nLq6tODlxTigvLTKBYEkxmMQt/yg4ZM=,iv:Lx3oRSpMPJLjcRhJujUNJzrPrp63MU1zS0CFd8iPJ+8=,tag:OsYXb22RcJxbEWm7jHLEMA==,type:str]
    pgp:
        - created_at: "2021-09-05T14:28:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6p3jCZcYZ8MAQ//TKznx4sOf2Mbr+H4iUy3MzjBcR/3V2NVOhUL3ihZehiv
            52xfRNOVnpvAxo6pX0gwrk8nW4rn9JNKffdZhXAYeR0gBDPeY5x/JQdM/WrZ1nLg
            HZ0YZang6EJWtrjtv6U84TriJ6DIY9IUnJ5e/n3f/QJBHOnIgHCvicc2GBIraWGe
            4QcqBQiRIe8rH2IRpWQH7C/FIkiMo7uUBf9yRIwcpEmtb2LiBoL6Lnb2GvuqqsDV
            cPT+WItvTsj8BROB5QVLBEkN6a3niD6IBorUAnENXfHtGdpRKG0k8ai/k7SXS5U+
            dYuiRzghPn60VhShlMnBhWYk40gkrOKFUJvn537ecqtFY9wRHbaonlrWRK51fIjB
            x8mED27TwZ1hC7xNxBgfwcgLdzX1KboP4uy5B593ynMDa2Kx13wKA4lsWS5WNum6
            3yE43piNiozaY4Y3XCnuMA5DOXjWp0RnjCLCkQI7eQ517ZsLBBaCKjIsUNIO4sDQ
            fay4a4XLTukHm4ecbhJrhMl2Fq3MqDqgJPT/pMIejDuEODsTT+tWsuT3ZCWkq7pC
            debMt3+F+q2z0xZ+EyP0RkCwxLJGJqlKRD45MePv3Z8qiczDeBE3X4AIbd2gJT8j
            yWQOiZe3i6aceEmOMUrgO+gR+TdpF3HNM5MztlmQ9bEjEpcO31uMRj64ePyREbLS
            XAHJ3q718Q4pqZH9wTddrV0sJ9iw4lY6W8nRsFVLelyoxrHhlKqrJuYnj/QmLLIh
            E/vrPQAySg+hJDCMIsDrVr45aIsKeUsYi/9d5rpWdaTb9hdckc2gb57GK8N6
            =zjJI
            -----END PGP MESSAGE-----
          fp: 473E92FCC1B19B623E24F1389F9D6BA271FF6A63
        - created_at: "2021-09-05T14:28:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1Mu2Wo4Op2VARAAj+pjy5/xWy5lsjMGbgiyQnILdGz+hdyzpcUoHTYzfvEE
            InzAlguzD3XeiCIFFZKFkac81H4L+C0S8dfUFFUzYfvRCxvrhoMah3yGUo2LYLgF
            Rdsl/2pkw+DyOrgb+QuC9Os2SEscmsVS8GiGOiRotN/u4gA0wjrn1apsE+Zem7TZ
            pDfH+xLgLjTUt2H9J4P1UGYPHEK92ZW2EltFiKAoXIONp388Ixkg6+JmDws2K649
            L0VsCgVgu3zRd4MK+fXyNnLLWAP/EaaSw93GbbKRWaIo3WGiHxRaamXAdNil/qVm
            fiM1M6tUpjwKO48QcvDSVQnSw2w6YigfvPJ1W2qmFcz0utk2TmalstNtJWXE5PMm
            uQ4Utn29s+IHltM1SAbxM8UarAHybOpWusrHyMCvN7Luww5kJj/YYmn9cb5bTGhS
            r1LQ1KfKOMWGQUyrq8IKEFzYa+fEU8RKd0yIiHeTMMz4G9JB0e3PqtHTMhfh01fH
            igk3tU+m+XblatzrqrfEQa1f6oyCBRQbNQ1sXbLgts1DRJhjlIyEtYtIqJMYepjm
            evOXlUWjI+NdS9ecc2udCOi7ssJ+qWqZqx7Ir/4YnLsMq0pf+6FwBlXuWUay4Jsc
            EboIuIjiUKoSwpi89bK6uQDE1PEwUrmtUXTe8OJZ5SVyTuZw5Yw1kuFIAMPVVxLS
            XAGSz/ZIG443O0V3akqz9gDlo/Te27LmBZPoGclFC17SScpRSeXoPFV/XqB8HUL9
            652uR+PRzzpZvQnOjMZpNaPokRJIX6YvzUN+SREm+luKWpNyNwhvtG3XJXGa
            =t61w
            -----END PGP MESSAGE-----
          fp: FC0B4DCED2CE5B598507991312C76065F613DD93
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
